test:
	PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, '/home/michael/xcb-perl/X11-XCB/lib/', '/home/michael/xcb-perl/X11-XCB/blib/lib', '/home/michael/xcb-perl/X11-XCB/blib/arch')" t/*.t

all: test
